[package]
name = "dynamic-programming"
version = "0.1.0"
authors = ["liujun <liujun@rxthinking.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
float-cmp = "0.9.0"
